# Generated by Django 5.1.4 on 2025-01-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hsk_level", models.IntegerField()),
                ("simplified", models.TextField()),
                ("radical", models.TextField()),
                ("frequency", models.IntegerField()),
                ("pos", models.JSONField(default=list)),
                ("traditional", models.TextField()),
                ("pinyin", models.TextField()),
                ("numeric_pinyin", models.TextField()),
                ("wade_giles", models.TextField()),
                ("bopomofo", models.TextField()),
                ("romatzyh", models.TextField()),
                ("meanings", models.JSONField(default=list)),
                ("classifiers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("hsk_level", "simplified", "pinyin")},
            },
        ),
        migrations.DeleteModel(
            name="HSK",
        ),
    ]
