# Generated by Django 5.1.4 on 2024-12-18 21:11

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="created_at",
        ),
        migrations.AddField(
            model_name="interest",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interest",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
