# Generated by Django 5.1.4 on 2025-01-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_remove_interest_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Metric",
        ),
    ]
