# Generated by Django 5.1.4 on 2025-01-06 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_delete_metric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Author of the post",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time of creation"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(
                default=False, help_text="Is the post published?"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time of last update"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="Markdown supported content"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Title of the post", max_length=200, unique=True
            ),
        ),
    ]
