# Generated by Django 5.1.4 on 2025-01-07 20:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0009_alter_post_options_post_author_post_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time of creation"
            ),
        ),
    ]
