# Generated by Django 5.1.4 on 2025-01-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_alter_post_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HSK",
        ),
    ]
