# Generated by Django 5.1.4 on 2025-01-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_hsk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HSK",
        ),
    ]
